### ISSUE TITLE
Running multiple ng: serve commands fails

### ISSUE THREAD

**Issue by talohana** [nrwl/angular-console#883]
I am following nrwl nx [tutorial](https://nx.dev/angular/tutorial/01-create-application) which contains multiple projects under the same `angular.json`.

<details>
<summary>The final angular.json</summary>

```json
{
  "version": 1,
  "projects": {
    "todos": {
      "projectType": "application",
      "schematics": {
        "@nrwl/angular:component": {
          "style": "scss"
        }
      },
      "root": "apps/todos",
      "sourceRoot": "apps/todos/src",
      "prefix": "nx-playground",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/apps/todos",
            "index": "apps/todos/src/index.html",
            "main": "apps/todos/src/main.ts",
            "polyfills": "apps/todos/src/polyfills.ts",
            "tsConfig": "apps/todos/tsconfig.app.json",
            "aot": false,
            "assets": ["apps/todos/src/favicon.ico", "apps/todos/src/assets"],
            "styles": ["apps/todos/src/styles.scss"],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/todos/src/environments/environment.ts",
                  "with": "apps/todos/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "todos:build",
            "proxyConfig": "apps/todos/proxy.conf.json"
          },
          "configurations": {
            "production": {
              "browserTarget": "todos:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "todos:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "apps/todos/tsconfig.app.json",
              "apps/todos/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**", "!apps/todos/**"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/todos/jest.config.js",
            "tsConfig": "apps/todos/tsconfig.spec.json",
            "setupFile": "apps/todos/src/test-setup.ts"
          }
        }
      }
    },
    "todos-e2e": {
      "root": "apps/todos-e2e",
      "sourceRoot": "apps/todos-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/todos-e2e/cypress.json",
            "tsConfig": "apps/todos-e2e/tsconfig.e2e.json",
            "devServerTarget": "todos:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "todos:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["apps/todos-e2e/tsconfig.e2e.json"],
            "exclude": ["**/node_modules/**", "!apps/todos-e2e/**"]
          }
        }
      }
    },
    "api": {
      "root": "apps/api",
      "sourceRoot": "apps/api/src",
      "projectType": "application",
      "prefix": "api",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@nrwl/node:build",
          "options": {
            "outputPath": "dist/apps/api",
            "main": "apps/api/src/main.ts",
            "tsConfig": "apps/api/tsconfig.app.json",
            "assets": ["apps/api/src/assets"]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/api/src/environments/environment.ts",
                  "with": "apps/api/src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@nrwl/node:execute",
          "options": {
            "buildTarget": "api:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "apps/api/tsconfig.app.json",
              "apps/api/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**", "!apps/api/**"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/api/jest.config.js",
            "tsConfig": "apps/api/tsconfig.spec.json"
          }
        }
      }
    },
    "data": {
      "root": "libs/data",
      "sourceRoot": "libs/data/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/data/tsconfig.lib.json",
              "libs/data/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**", "!libs/data/**"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/data/jest.config.js",
            "tsConfig": "libs/data/tsconfig.spec.json"
          }
        }
      }
    },
    "ui": {
      "projectType": "library",
      "root": "libs/ui",
      "sourceRoot": "libs/ui/src",
      "prefix": "nx-playground",
      "architect": {
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/ui/tsconfig.lib.json",
              "libs/ui/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**", "!libs/ui/**"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/ui/jest.config.js",
            "tsConfig": "libs/ui/tsconfig.spec.json",
            "setupFile": "libs/ui/src/test-setup.ts"
          }
        }
      },
      "schematics": {
        "@nrwl/angular:component": {
          "styleext": "scss"
        }
      }
    }
  },
  "cli": {
    "defaultCollection": "@nrwl/angular"
  },
  "schematics": {
    "@nrwl/angular:application": {
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "unitTestRunner": "jest"
    }
  },
  "defaultProject": "todos"
}
```
</details>

The problem is, when i'm trying to run multiple `ng: serve` tasks w/o the ui, the only first one, for example the `todos`, succeeded, after running another `ng: serve` but now choosing different project, for example the `api`, i'm getting the error:

![image](https://user-images.githubusercontent.com/24203431/68745345-30198680-05ff-11ea-8481-f70812a60992.png)

When in fact I ran `ng: serve` only for the `todos` project.

Thanks!

**Comment by mrmeku** [comment]
@talohana Thanks for pointing that out! We'll get that squared away

**Comment by ctaleck** [comment]
Adding message as text instead of screen shot so it is searchable!

> The task 'angular-console: ng serve app (app)' is already active.

Will look for the update now that I know it is fixed.

**Comment by talohana** [comment]
@ctaleck It's still seems broken for me, could you update please?

**Comment by talohana** [comment]
> @talohana Thanks for pointing that out! We'll get that squared away

It seems that the problem is reproducing, with:
> The task 'angular-console: ng serve api (project-folder)' is already active

Even though I ran only ng serve with the `todos`

**Comment by dandean** [comment]
This is still happening on version 11.1.3

<img width="459" alt="image" src="https://user-images.githubusercontent.com/18332/79517832-3b386e80-8004-11ea-9b20-4b9842aef0fb.png">

**Comment by ericsnap** [comment]
I am running in this issue myself `v14.0.1`. @jaysoo can you confirm that the fix was working and is still working?

**Comment by mackelito** [comment]
I can confirm this issue with a new installation/setup

**Comment by likeuwill** [comment]
You can run for example server and client by adding to nx common commands
`nx run-many --target=serve --projects=server,client --parallel`
